version: '3.8'

services:
  db-booking:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: BookingCar
    environment:
      SA_PASSWORD: "Lyly2505"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_booking_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - rental-network
    # (Tuỳ chọn) thêm healthcheck cho SQL Server nếu image hỗ trợ công cụ kiểm tra
    # healthcheck:
    #   test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$SA_PASSWORD\" -Q \"SELECT 1\" || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  booking_service:
    build:
      context: ./booking_service
      dockerfile: Dockerfile
    container_name: rental-booking-service
    restart: unless-stopped
    ports:
      - "8003:8003"
    environment:
      - SQL_DB=rental_user_db
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - DB_HOST=db-booking
      - DB_PORT=1433
    depends_on:
      - db-booking
    networks:
      - rental-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sqlserver_booking_data:
    driver: local

networks:
  rental-network:
    driver: bridge